/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export enum Language {
  ENGLISH = 'English',
  HINDI = 'Hindi',
  PUNJABI = 'Punjabi',
  MARATHI = 'Marathi',
  TELUGU = 'Telugu',
  BENGALI = 'Bengali',
  ODIA = 'Odia',
}

export interface KisanDostResponse {
  greeting: string;
  answer: string;
  proTips: string[];
  audioSummary: string;
  safetySection?: string;
  mandiPrices?: {
    crop: string;
    market: string;
    price: string;
    trend: 'up' | 'down' | 'stable';
  }[];
  schemes?: {
    name: string;
    benefit: string;
    link: string;
  }[];
}

export interface ExpenseRecord {
  id: string;
  date: string;
  category: 'Seeds' | 'Fertilizer' | 'Pesticide' | 'Labor' | 'Fuel' | 'Other';
  amount: number;
  description: string;
}

export interface ChatMessage {
  role: 'user' | 'model';
  parts: { text: string }[];
}

export interface SoilReport {
  nitrogen: string;
  phosphorus: string;
  potassium: string;
  ph: string;
  recommendation: string;
}

export interface DiagnosisRecord {
  id: string;
  uid: string;
  timestamp: string;
  query?: string;
  diagnosis: string;
  imageUrl?: string | null;
}

export const LANGUAGES = [
  { id: Language.ENGLISH, label: 'English' },
  { id: Language.HINDI, label: 'हिन्दी (Hindi)' },
  { id: Language.PUNJABI, label: 'ਪੰਜਾਬੀ (Punjabi)' },
  { id: Language.MARATHI, label: 'मराठी (Marathi)' },
  { id: Language.TELUGU, label: 'తెలుగు (Telugu)' },
  { id: Language.BENGALI, label: 'বাংলা (Bengali)' },
  { id: Language.ODIA, label: 'ଓଡ଼ିଆ (Odia)' },
];

export const UI_LABELS: Record<string, any> = {
  [Language.HINDI]: {
    welcome: "किसान-दोस्त में आपका स्वागत है",
    ask_query: "सवाल पूछें (आवाज़/लिखकर)",
    check_mandi: "मंडी भाव देखें",
    weather_update: "मौसम का पूर्वानुमान",
    upload_crop_photo: "फसल की फोटो भेजें",
    gov_schemes: "सरकारी योजनाएं",
    safety_warning: "सुरक्षा चेतावनी",
    submit: "जमा करें",
    history: "इतिहास",
    khata: "खाता",
    market: "बाजार",
    field: "खेत",
    soil: "मिट्टी",
    advisor: "सलाहकार",
    login_google: "गूगल के साथ लॉगिन करें",
    digital_khata: "डिजिटल खाता",
    add_expense: "नया खर्च जोड़ें",
    recent_transactions: "हाल के लेनदेन",
    no_transactions: "अभी तक कोई लेनदेन नहीं।",
    soil_health_card: "मिट्टी स्वास्थ्य कार्ड",
    upload_report: "रिपोर्ट अपलोड करें",
    companion: "आपका कृषि साथी",
    login: "लॉगिन",
    logout: "लॉगआउट",
    suggestions: [
      "पंजाब में गेहूं बोने का सबसे अच्छा समय?",
      "कपास में कीटों को कैसे नियंत्रित करें?",
      "इस मौसम में चावल के लिए कौन सा उर्वरक?",
      "जैविक खेती के लिए मिट्टी स्वास्थ्य युक्तियाँ"
    ],
    consulting: "आपके लिए विशेषज्ञों से सलाह ले रहे हैं...",
    error_title: "ओह! कुछ गलत हो गया",
    try_again: "फिर से प्रयास करें",
    safety_first: "सुरक्षा सर्वोपरि",
    live_mandi: "लाइव मंडी भाव",
    learn_more: "और जानें",
    pro_tip: "प्रो-टिप",
    describe_issue: "समस्या का वर्णन करें...",
    voice_input: "आवाज़ इनपुट",
    analyzing_image: "छवि का विश्लेषण कर रहे हैं...",
    clear_text: "टेक्स्ट साफ़ करें",
    reset_chat: "चैट संदर्भ रीसेट करें",
    audio_summary: "ऑडियो सारांश",
    total_expenses: "कुल खर्च",
    trending_crops: "ट्रेंडिंग फसलें",
    market_audio_info: "बाजार ऑडियो जानकारी",
    history_title: "निदान इतिहास",
    no_history: "कोई इतिहास नहीं मिला।",
    satellite_map: "सैटेलाइट स्वास्थ्य मानचित्र (NDVI)",
    field_stress: "खेत में तनाव का पता चला",
    soil_parameters: "मिट्टी के पैरामीटर",
    login_history: "इतिहास देखने के लिए लॉगिन करें",
    remove_image: "फोटो हटाएं",
    verify_kvk: "KVK से सत्यापित करें",
    general_info: "सामान्य जानकारी",
    image_selected: "विश्लेषण के लिए फोटो चुनी गई",
    add_expense_title: "खर्च जोड़ें",
    category: "श्रेणी",
    amount: "राशि (₹)",
    description: "विवरण",
    optional_details: "वैकल्पिक विवरण...",
    cancel: "रद्द करें",
    saving: "सहेज रहे हैं...",
    save_record: "रिकॉर्ड सहेजें",
    terms_conditions: "नियम और शर्तें",
    terms_title: "किसान-दोस्त की शर्तें",
    i_understand: "मैं समझता हूँ",
    read_aloud: "बोलकर सुनें",
    setup_api_key: "एपीआई कुंजी सेटअप करें",
    api_key_desc: "सेवा जारी रखने के लिए कृपया अपनी भुगतान की गई जेमिनी एपीआई कुंजी चुनें।",
    select_key: "कुंजी चुनें"
  },
  [Language.TELUGU]: {
    welcome: "కిసాన్-దోస్త్ కు స్వాగతం",
    ask_query: "ప్రశ్న అడగండి (వాయిస్/టెక్స్ట్)",
    check_mandi: "మండీ ధరలు చూడండి",
    weather_update: "వాతావరణ సూచన",
    upload_crop_photo: "పంట ఫోటోను అప్లోడ్ చేయండి",
    gov_schemes: "ప్రభుత్వ పథకాలు",
    safety_warning: "భద్రతా హెచ్చరిక",
    submit: "సమర్పించండి",
    history: "చరిత్ర",
    khata: "ఖాతా",
    market: "మార్కెట్",
    field: "పొలం",
    soil: "నేల",
    advisor: "సలహాదారు",
    login_google: "గూగుల్ తో లాగిన్ అవ్వండి",
    digital_khata: "డిజిటల్ ఖాతా",
    add_expense: "కొత్త ఖర్చును జోడించండి",
    recent_transactions: "ఇటీవలి లావాదేవీలు",
    no_transactions: "ఇంకా లావాదేవీలు లేవు.",
    soil_health_card: "నేల ఆరోగ్య కార్డు",
    upload_report: "నివేదికను అప్లోడ్ చేయండి",
    companion: "మీ వ్యవసాయ సహచరుడు",
    login: "లాగిన్",
    logout: "లాగ్ అవుట్",
    suggestions: [
      "పంజాబ్‌లో గోధుమలు విత్తడానికి ఉత్తమ సమయం?",
      "పత్తిలో తెగుళ్లను ఎలా నియంత్రించాలి?",
      "ఈ సీజన్‌లో వరికి ఏ ఎరువులు వాడాలి?",
      "సేంద్రీయ వ్యవసాయం కోసం నేల ఆరోగ్య చిట్కాలు"
    ],
    consulting: "మీ కోసం నిపుణులను సంప్రదిస్తున్నాము...",
    error_title: "అయ్యో! ఏదో తప్పు జరిగింది",
    try_again: "మళ్ళీ ప్రయత్నించండి",
    safety_first: "భద్రతే ముఖ్యం",
    live_mandi: "లైవ్ మండీ ధరలు",
    learn_more: "మరింత తెలుసుకోండి",
    pro_tip: "ప్రో-టిప్",
    describe_issue: "సమస్యను వివరించండి...",
    voice_input: "వాయిస్ ఇన్‌పుట్",
    analyzing_image: "చిత్రాన్ని విశ్లేషిస్తోంది...",
    clear_text: "టెక్స్ట్ క్లియర్ చేయండి",
    reset_chat: "చాట్ సందర్భాన్ని రీసెట్ చేయండి",
    audio_summary: "ఆడియో సారాంశం",
    total_expenses: "మొత్తం ఖర్చులు",
    trending_crops: "ట్రెండింగ్ పంటలు",
    market_audio_info: "మార్కెట్ ఆడియో సమాచారం",
    history_title: "రోగ నిర్ధారణ చరిత్ర",
    no_history: "చరిత్ర కనుగొనబడలేదు.",
    satellite_map: "శాటిలైట్ హెల్త్ మ్యాప్ (NDVI)",
    field_stress: "ఫీల్డ్ స్ట్రెస్ గుర్తించబడింది",
    soil_parameters: "నేల పారామితులు",
    login_history: "చరిత్రను చూడటానికి లాగిన్ చేయండి",
    remove_image: "చిత్రాన్ని తొలగించండి",
    verify_kvk: "KVKతో ధృవీకరించండి",
    general_info: "సాధారణ సమాచారం",
    image_selected: "విశ్లేషణ కోసం చిత్రం ఎంపిక చేయబడింది",
    add_expense_title: "ఖర్చును జోడించండి",
    category: "వర్గం",
    amount: "మొత్తం (₹)",
    description: "వివరణ",
    optional_details: "ఐచ్ఛిక వివరాలు...",
    cancel: "రద్దు చేయి",
    saving: "సేవ్ చేస్తోంది...",
    save_record: "రికార్డును సేవ్ చేయి",
    terms_conditions: "నిబంధనలు మరియు షరతులు",
    terms_title: "కిసాన్-దోస్త్ నిబంధనలు",
    i_understand: "నాకు అర్థమైంది",
    read_aloud: "బిగ్గరగా చదవండి",
    setup_api_key: "API కీని సెటప్ చేయండి",
    api_key_desc: "సేవను కొనసాగించడానికి దయచేసి మీ చెల్లింపు జెమిని API కీని ఎంచుకోండి.",
    select_key: "కీని ఎంచుకోండి"
  },
  [Language.MARATHI]: {
    welcome: "किसान-दोस्त मध्ये आपले स्वागत आहे",
    ask_query: "प्रश्न विचारा (आवाज/लिखाण)",
    check_mandi: "मंडी दर तपासा",
    weather_update: "हवामान अंदाज",
    upload_crop_photo: "पीक फोटो अपलोड करा",
    gov_schemes: "सरकारी योजना",
    safety_warning: "सुरक्षा इशारा",
    submit: "सादर करा",
    history: "इतिहास",
    khata: "खाते",
    market: "बाजार",
    field: "शेत",
    soil: "माती",
    advisor: "सल्लागार",
    login_google: "गूगलसह लॉगिन करा",
    digital_khata: "डिजिटल खाते",
    add_expense: "नवीन खर्च जोडा",
    recent_transactions: "अलीकडील व्यवहार",
    no_transactions: "अद्याप कोणतेही व्यवहार नाहीत.",
    soil_health_card: "मृदा आरोग्य कार्ड",
    upload_report: "अहवाल अपलोड करा",
    companion: "तुमचा कृषी सोबती",
    login: "लॉगिन",
    logout: "लॉगआउट",
    suggestions: [
      "पंजाबमध्ये गहू पेरण्याची सर्वोत्तम वेळ?",
      "कापसातील किडींचे नियंत्रण कसे करावे?",
      "या हंगामात भातासाठी कोणते खत वापरावे?",
      "सेंद्रिय शेतीसाठी माती आरोग्य टिप्स"
    ],
    consulting: "तुमच्यासाठी तज्ञांचा सल्ला घेत आहोत...",
    error_title: "ओह! काहीतरी चुकले",
    try_again: "पुन्हा प्रयत्न करा",
    safety_first: "सुरक्षा प्रथम",
    live_mandi: "थेट मंडी दर",
    learn_more: "अधिक जाणून घ्या",
    pro_tip: "प्रो-टिप",
    describe_issue: "समस्येचे वर्णन करा...",
    voice_input: "व्हॉइस इनपुट",
    analyzing_image: "प्रतिमेचे विश्लेषण करत आहे...",
    clear_text: "मजकूर साफ करा",
    reset_chat: "चॅट संदर्भ रीसेट करा",
    audio_summary: "ऑडिओ सारांश",
    total_expenses: "एकूण खर्च",
    trending_crops: "ट्रेंडिंग पिके",
    market_audio_info: "बाजार ऑडिओ माहिती",
    history_title: "निदान इतिहास",
    no_history: "इतिहास सापडला नाही.",
    satellite_map: "सॅटेलाईट आरोग्य नकाशा (NDVI)",
    field_stress: "शेतात ताण आढळला",
    soil_parameters: "मातीचे घटक",
    login_history: "इतिहास पाहण्यासाठी लॉगिन करा",
    remove_image: "फोटो काढा",
    verify_kvk: "KVK कडून सत्यापित करा",
    general_info: "सामान्य माहिती",
    image_selected: "विश्लेषणासाठी फोटो निवडला",
    add_expense_title: "खर्च जोडा",
    category: "वर्ग",
    amount: "रक्कम (₹)",
    description: "वर्णन",
    optional_details: "पर्यायी तपशील...",
    cancel: "रद्द करा",
    saving: "जतन करत आहे...",
    save_record: "रेकॉर्ड जतन करा",
    terms_conditions: "नियम आणि अटी",
    terms_title: "किसान-दोस्त अटी",
    i_understand: "मला समजले",
    read_aloud: "मोठ्याने वाचा"
  },
  [Language.BENGALI]: {
    welcome: "কিষাণ-দোস্ত-এ স্বাগতম",
    ask_query: "প্রশ্ন জিজ্ঞাসা করুন (ভয়েস/টেক্সট)",
    check_mandi: "মান্ডি দর দেখুন",
    weather_update: "আবহাওয়ার পূর্বাভাস",
    upload_crop_photo: "ফসলের ছবি আপলোড করুন",
    gov_schemes: "সরকারি প্রকল্প",
    safety_warning: "সুরক্ষা সতর্কতা",
    submit: "জমা দিন",
    history: "ইতিহাস",
    khata: "খাতা",
    market: "বাজার",
    field: "মাঠ",
    soil: "মাটি",
    advisor: "উপদেষ্টা",
    login_google: "গুগল দিয়ে লগইন করুন",
    digital_khata: "ডিজিটাল খাতা",
    add_expense: "নতুন খরচ যোগ করুন",
    recent_transactions: "সাম্প্রতিক লেনদেন",
    no_transactions: "এখনও কোন লেনদেন নেই।",
    soil_health_card: "মাটি স্বাস্থ্য কার্ড",
    upload_report: "রিপোর্ট আপলোড করুন",
    companion: "আপনার কৃষি সঙ্গী",
    login: "লগইন",
    logout: "লগআউট",
    suggestions: [
      "পাঞ্জাবে গম বোনার উপযুক্ত সময় কবে?",
      "তুলায় পোকা নিয়ন্ত্রণ করবেন কীভাবে?",
      "এই মরসুমে ধানের জন্য কোন সার ব্যবহার করবেন?",
      "জৈব চাষের জন্য মাটির স্বাস্থ্যের টিপস"
    ],
    consulting: "আপনার জন্য বিশেষজ্ঞদের পরামর্শ নিচ্ছি...",
    error_title: "ওহ! কিছু ভুল হয়েছে",
    try_again: "আবার চেষ্টা করুন",
    safety_first: "সুরক্ষা আগে",
    live_mandi: "লাইভ মান্ডি দর",
    learn_more: "আরও জানুন",
    pro_tip: "প্রো-টিপ",
    describe_issue: "সমস্যা বর্ণনা করুন...",
    voice_input: "ভয়েস ইনপুট",
    analyzing_image: "ছবি বিশ্লেষণ করা হচ্ছে...",
    clear_text: "টেক্সট মুছে ফেলুন",
    reset_chat: "চ্যাট প্রসঙ্গ রিসেট করুন",
    audio_summary: "অডিও সারাংশ",
    total_expenses: "মোট খরচ",
    trending_crops: "ট্রেন্ডিং ফসল",
    market_audio_info: "বাজার অডিও তথ্য",
    history_title: "রোগ নির্ণয়ের ইতিহাস",
    no_history: "কোন ইতিহাস পাওয়া যায়নি।",
    satellite_map: "স্যাটেলাইট স্বাস্থ্য মানচিত্র (NDVI)",
    field_stress: "মাঠে স্ট্রেস শনাক্ত হয়েছে",
    soil_parameters: "মাটির প্যারামিটার",
    login_history: "ইতিহাস দেখতে লগইন করুন",
    remove_image: "ছবি সরান",
    verify_kvk: "KVK-এর সাথে যাচাই করুন",
    general_info: "সাধারণ তথ্য",
    image_selected: "বিশ্লেষণের জন্য ছবি নির্বাচন করা হয়েছে",
    add_expense_title: "খরচ যোগ করুন",
    category: "বিভাগ",
    amount: "পরিমাণ (₹)",
    description: "বিবরণ",
    optional_details: "ঐচ্ছিক বিবরণ...",
    cancel: "বাতিল করুন",
    saving: "সংরক্ষণ করা হচ্ছে...",
    save_record: "রেকর্ড সংরক্ষণ করুন",
    terms_conditions: "শর্তাবলী",
    terms_title: "কিষাণ-দোস্ত শর্তাবলী",
    i_understand: "আমি বুঝতে পেরেছি",
    read_aloud: "জোরে পড়ুন"
  },
  [Language.PUNJABI]: {
    welcome: "ਕਿਸਾਨ-ਦੋਸਤ ਵਿੱਚ ਤੁਹਾਡਾ ਸੁਆਗਤ ਹੈ",
    ask_query: "ਸਵਾਲ ਪੁੱਛੋ (ਆਵਾਜ਼/ਲਿਖ ਕੇ)",
    check_mandi: "ਮੰਡੀ ਦੇ ਭਾਅ ਦੇਖੋ",
    weather_update: "ਮੌਸਮ ਦੀ ਭਵਿੱਖਬਾਣੀ",
    upload_crop_photo: "ਫਸਲ ਦੀ ਫੋਟੋ ਅਪਲੋਡ ਕਰੋ",
    gov_schemes: "ਸਰਕਾਰੀ ਸਕੀਮਾਂ",
    safety_warning: "ਸੁਰੱਖਿਆ ਚੇਤਾਵਨੀ",
    submit: "ਜਮ੍ਹਾਂ ਕਰੋ",
    history: "ਇਤਿਹਾਸ",
    khata: "ਖਾਤਾ",
    market: "ਬਾਜ਼ਾਰ",
    field: "ਖੇਤ",
    soil: "ਮਿੱਟੀ",
    advisor: "ਸਲਾਹਕਾਰ",
    login_google: "ਗੂਗਲ ਨਾਲ ਲੋਗਿਨ ਕਰੋ",
    digital_khata: "ਡਿਜੀਟਲ ਖਾਤਾ",
    add_expense: "ਨਵਾਂ ਖਰਚਾ ਜੋੜੋ",
    recent_transactions: "ਹਾਲੀਆ ਲੈਣ-ਦੇਣ",
    no_transactions: "ਅਜੇ ਤੱਕ ਕੋਈ ਲੈਣ-ਦੇਣ ਨਹੀਂ।",
    soil_health_card: "ਮਿੱਟੀ ਸਿਹਤ ਕਾਰਡ",
    upload_report: "ਰਿਪੋਰਟ ਅਪਲੋਡ ਕਰੋ",
    companion: "ਤੁਹਾਡਾ ਖੇਤੀਬਾੜੀ ਸਾਥੀ",
    login: "ਲੋਗਿਨ",
    logout: "ਲੋਗਆਉਟ",
    suggestions: [
      "ਪੰਜਾਬ ਵਿੱਚ ਕਣਕ ਬੀਜਣ ਦਾ ਸਭ ਤੋਂ ਵਧੀਆ ਸਮਾਂ?",
      "ਕਪਾਹ ਵਿੱਚ ਕੀੜਿਆਂ ਨੂੰ ਕਿਵੇਂ ਕਾਬੂ ਕਰੀਏ?",
      "ਇਸ ਸੀਜ਼ਨ ਵਿੱਚ ਝੋਨੇ ਲਈ ਕਿਹੜੀ ਖਾਦ?",
      "ਜੈਵਿਕ ਖੇਤੀ ਲਈ ਮਿੱਟੀ ਦੀ ਸਿਹਤ ਦੇ ਨੁਕਤੇ"
    ],
    consulting: "ਤੁਹਾਡੇ ਲਈ ਮਾਹਿਰਾਂ ਤੋਂ ਸਲਾਹ ਲੈ ਰਹੇ ਹਾਂ...",
    error_title: "ਓਹ! ਕੁਝ ਗਲਤ ਹੋ ਗਿਆ",
    try_again: "ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ",
    safety_first: "ਸੁਰੱਖਿਆ ਪਹਿਲਾਂ",
    live_mandi: "ਲਾਈਵ ਮੰਡੀ ਭਾਅ",
    learn_more: "ਹੋਰ ਜਾਣੋ",
    pro_tip: "ਪ੍ਰੋ-ਟਿਪ",
    describe_issue: "ਸਮੱਸਿਆ ਦਾ ਵਰਣਨ ਕਰੋ...",
    voice_input: "ਆਵਾਜ਼ ਇਨਪੁਟ",
    analyzing_image: "ਤਸਵੀਰ ਦਾ ਵਿਸ਼ਲੇਸ਼ਣ ਕਰ ਰਹੇ ਹਾਂ...",
    clear_text: "ਟੈਕਸਟ ਸਾਫ਼ ਕਰੋ",
    reset_chat: "ਚੈਟ ਪ੍ਰਸੰਗ ਰੀਸੈਟ ਕਰੋ",
    audio_summary: "ਆਡੀਓ ਸਾਰ",
    total_expenses: "ਕੁੱਲ ਖਰਚੇ",
    trending_crops: "ਪ੍ਰਚਲਿਤ ਫਸਲਾਂ",
    market_audio_info: "ਮਾਰਕੀਟ ਆਡੀਓ ਜਾਣਕਾਰੀ",
    history_title: "ਨਿਦਾਨ ਇਤਿਹਾਸ",
    no_history: "ਕੋਈ ਇਤਿਹਾਸ ਨਹੀਂ ਮਿਲਿਆ।",
    satellite_map: "ਸੈਟੇਲਾਈਟ ਸਿਹਤ ਨਕਸ਼ਾ (NDVI)",
    field_stress: "ਖੇਤ ਵਿੱਚ ਤਣਾਅ ਦਾ ਪਤਾ ਲੱਗਾ",
    soil_parameters: "ਮਿੱਟੀ ਦੇ ਮਾਪਦੰਡ",
    login_history: "ਇਤਿਹਾਸ ਦੇਖਣ ਲਈ ਲੌਗਇਨ ਕਰੋ",
    remove_image: "ਫੋਟੋ ਹਟਾਓ",
    verify_kvk: "KVK ਨਾਲ ਪੁਸ਼ਟੀ ਕਰੋ",
    general_info: "ਆਮ ਜਾਣਕਾਰੀ",
    image_selected: "ਵਿਸ਼ਲੇਸ਼ਣ ਲਈ ਫੋਟੋ ਚੁਣੀ ਗਈ",
    add_expense_title: "ਖਰਚਾ ਜੋੜੋ",
    category: "ਸ਼੍ਰੇਣੀ",
    amount: "ਰਕਮ (₹)",
    description: "ਵੇਰਵਾ",
    optional_details: "ਵਿਕਲਪਿਕ ਵੇਰਵੇ...",
    cancel: "ਰੱਦ ਕਰੋ",
    saving: "ਸੇਵ ਕਰ ਰਿਹਾ ਹੈ...",
    save_record: "ਰਿਕਾਰਡ ਸੇਵ ਕਰੋ",
    terms_conditions: "ਨਿਯਮ ਅਤੇ ਸ਼ਰਤਾਂ",
    terms_title: "ਕਿਸਾਨ-ਦੋਸਤ ਦੀਆਂ ਸ਼ਰਤਾਂ",
    i_understand: "ਮੈਂ ਸਮਝਦਾ ਹਾਂ",
    read_aloud: "ਉੱਚੀ ਪੜ੍ਹੋ"
  },
  [Language.TAMIL]: {
    welcome: "கிசான் தோஸ்த் உங்களை வரவேற்கிறது",
    ask_query: "உங்கள் கேள்வியைக் கேளுங்கள்",
    check_mandi: "மண்டி விலையை பார்க்கவும்",
    weather_update: "வானிலை நிலவரம்",
    upload_crop_photo: "பயிரின் புகைப்படத்தை அனுப்பவும்",
    gov_schemes: "அரசு திட்டங்கள்",
    safety_warning: "பாதுகாப்பு எச்சரிக்கை",
    submit: "சமர்ப்பிக்கவும்",
    history: "வரலாறு",
    khata: "கணக்கு",
    market: "சந்தை",
    field: "வயல்",
    soil: "மண்",
    advisor: "ஆலோசகர்",
    login_google: "கூகுள் மூலம் உள்நுழையவும்",
    digital_khata: "டிஜிட்டல் கணக்கு",
    add_expense: "புதிய செலவைச் சேர்க்கவும்",
    recent_transactions: "சமீபத்திய பரிவர்த்தனைகள்",
    no_transactions: "இதுவரை பரிவர்த்தனைகள் இல்லை.",
    soil_health_card: "மண் சுகாதார அட்டை",
    upload_report: "அறிக்கையை பதிவேற்றவும்",
    companion: "உங்கள் விவசாய தோழன்",
    login: "உள்நுழைய",
    logout: "வெளியேறு",
    suggestions: [
      "பஞ்சாபில் கோதுமை விதைக்க சிறந்த நேரம்?",
      "பருத்தியில் பூச்சிகளை எவ்வாறு கட்டுப்படுத்துவது?",
      "இந்த பருவத்தில் நெல்லுக்கு எந்த உரம்?",
      "இயற்கை விவசாயத்திற்கான மண் சுகாதார குறிப்புகள்"
    ],
    consulting: "உங்களுக்காக நிபுணர்களிடம் ஆலோசிக்கிறோம்...",
    error_title: "ஓ! ஏதோ தவறு நடந்துவிட்டது",
    try_again: "மீண்டும் முயற்சிக்கவும்",
    safety_first: "பாதுகாப்பு முதலில்",
    live_mandi: "நேரடி மண்டி விலைகள்",
    learn_more: "மேலும் அறிக",
    pro_tip: "ப்ரோ-டிப்",
    describe_issue: "சிக்கலை விவரிக்கவும்...",
    voice_input: "குரல் உள்ளீடு",
    analyzing_image: "படத்தை பகுப்பாய்வு செய்கிறது...",
    clear_text: "உரையை அழிக்கவும்",
    reset_chat: "அரட்டை சூழலை மீட்டமைக்கவும்",
    audio_summary: "ஆடியோ சுருக்கம்",
    total_expenses: "மொத்த செலவுகள்",
    trending_crops: "பிரபலமான பயிர்கள்",
    market_audio_info: "சந்தை ஆடியோ தகவல்",
    history_title: "கண்டறிதல் வரலாறு",
    no_history: "வரலாறு எதுவும் கிடைக்கவில்லை.",
    satellite_map: "செயற்கைக்கோள் சுகாதார வரைபடம் (NDVI)",
    field_stress: "வயலில் அழுத்தம் கண்டறியப்பட்டது",
    soil_parameters: "மண் அளவுருக்கள்",
    login_history: "வரலாற்றைக் காண உள்நுழையவும்",
    remove_image: "படத்தை அகற்று",
    verify_kvk: "KVK உடன் சரிபார்க்கவும்",
    general_info: "பொது தகவல்",
    image_selected: "பகுப்பாய்விற்காக படம் தேர்ந்தெடுக்கப்பட்டது",
    add_expense_title: "செலவைச் சேர்க்கவும்",
    category: "வகை",
    amount: "தொகை (₹)",
    description: "விளக்கம்",
    optional_details: "விருப்ப விவரங்கள்...",
    cancel: "ரத்துசெய்",
    saving: "சேமிக்கிறது...",
    save_record: "பதிவைச் சேமி",
    terms_conditions: "விதிமுறைகள் மற்றும் நிபந்தனைகள்",
    terms_title: "கிசான்-தோஸ்த் விதிமுறைகள்",
    i_understand: "நான் புரிந்துகொள்கிறேன்",
    read_aloud: "சத்தமாக வாசிக்கவும்",
    setup_api_key: "API விசையை அமைக்கவும்",
    api_key_desc: "சேவையைத் தொடர உங்கள் கட்டண ஜெமினி API விசையைத் தேர்ந்தெடுக்கவும்.",
    select_key: "விசையைத் தேர்ந்தெடுக்கவும்"
  },
  [Language.KANNADA]: {
    welcome: "ಕಿಸಾನ್ ದೋಸ್ತ್ ಗೆ ಸುಸ್ವಾಗತ",
    ask_query: "ನಿಮ್ಮ ಪ್ರಶ್ನೆಯನ್ನು ಕೇಳಿ",
    check_mandi: "ಮಾರುಕಟ್ಟೆ ಬೆಲೆ ನೋಡಿ",
    weather_update: "ಹವಾಮಾನ ಮುನ್ಸೂಚನೆ",
    upload_crop_photo: "ಬೆಳೆಯ ಫೋಟೋ ಕಳುಹಿಸಿ",
    gov_schemes: "ಸರ್ಕಾರಿ ಯೋಜನೆಗಳು",
    safety_warning: "ಸುರಕ್ಷತಾ ಎಚ್ಚರಿಕೆ",
    submit: "ಸಲ್ಲಿಸಿ",
    history: "ಇತಿಹಾಸ",
    khata: "ಖಾತೆ",
    market: "ಮಾರುಕಟ್ಟೆ",
    field: "ಹೊಲ",
    soil: "ಮಣ್ಣು",
    advisor: "ಸಲಹೆಗಾರ",
    login_google: "ಗೂಗಲ್‌ನೊಂದಿಗೆ ಲಾಗಿನ್ ಮಾಡಿ",
    digital_khata: "ಡಿಜಿಟಲ್ ಖಾತೆ",
    add_expense: "ಹೊಸ ಖರ್ಚನ್ನು ಸೇರಿಸಿ",
    recent_transactions: "ಇತ್ತೀಚಿನ ವಹಿವಾಟುಗಳು",
    no_transactions: "ಇನ್ನೂ ಯಾವುದೇ ವಹಿವಾಟುಗಳಿಲ್ಲ.",
    soil_health_card: "ಮಣ್ಣಿನ ಆರೋಗ್ಯ ಕಾರ್ಡ್",
    upload_report: "ವರದಿಯನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
    companion: "ನಿಮ್ಮ ಕೃಷಿ ಒಡನಾಡಿ",
    login: "ಲಾಗಿನ್",
    logout: "ಲಾಗ್ ಔಟ್",
    suggestions: [
      "ಪಂಜಾಬ್‌ನಲ್ಲಿ ಗೋಧಿ ಬಿತ್ತಲು ಉತ್ತಮ ಸಮಯ?",
      "ಹತ್ತಿಯಲ್ಲಿ ಕೀಟಗಳನ್ನು ನಿಯಂತ್ರಿಸುವುದು ಹೇಗೆ?",
      "ಈ ಋತುವಿನಲ್ಲಿ ಭತ್ತಕ್ಕೆ ಯಾವ ರಸಗೊಬ್ಬರ?",
      "ಸಾವಯವ ಕೃಷಿಗಾಗಿ ಮಣ್ಣಿನ ಆರೋಗ್ಯ ಸಲಹೆಗಳು"
    ],
    consulting: "ನಿಮಗಾಗಿ ತಜ್ಞರನ್ನು ಸಂಪರ್ಕಿಸುತ್ತಿದ್ದೇವೆ...",
    error_title: "ಓಹ್! ಏನೋ ತಪ್ಪಾಗಿದೆ",
    try_again: "ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ",
    safety_first: "ಸುರಕ್ಷತೆ ಮೊದಲು",
    live_mandi: "ಲೈವ್ ಮಂಡಿ ಬೆಲೆಗಳು",
    learn_more: "ಇನ್ನಷ್ಟು ತಿಳಿಯಿರಿ",
    pro_tip: "ಪ್ರೊ-ಟಿಪ್",
    describe_issue: "ಸಮಸ್ಯೆಯನ್ನು ವಿವರಿಸಿ...",
    voice_input: "ಧ್ವನಿ ಇನ್ಪುಟ್",
    analyzing_image: "ಚಿತ್ರವನ್ನು ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ...",
    clear_text: "ಪಠ್ಯವನ್ನು ತೆರವುಗೊಳಿಸಿ",
    reset_chat: "ಚಾಟ್ ಸಂದರ್ಭವನ್ನು ಮರುಹೊಂದಿಸಿ",
    audio_summary: "ಆಡಿಯೋ ಸಾರಾಂಶ",
    total_expenses: "ಒಟ್ಟು ಖರ್ಚುಗಳು",
    trending_crops: "ಟ್ರೆಂಡಿಂಗ್ ಬೆಳೆಗಳು",
    market_audio_info: "ಮಾರುಕಟ್ಟೆ ಆಡಿಯೋ ಮಾಹಿತಿ",
    history_title: "ರೋಗನಿರ್ಣಯದ ಇತಿಹಾಸ",
    no_history: "ಯಾವುದೇ ಇತಿಹಾಸ ಕಂಡುಬಂದಿಲ್ಲ.",
    satellite_map: "ಉಪಗ್ರಹ ಆರೋಗ್ಯ ನಕ್ಷೆ (NDVI)",
    field_stress: "ಹೊಲದಲ್ಲಿ ಒತ್ತಡ ಪತ್ತೆಯಾಗಿದೆ",
    soil_parameters: "ಮಣ್ಣಿನ ನಿಯತಾಂಕಗಳು",
    login_history: "ಇತಿಹಾಸವನ್ನು ವೀಕ್ಷಿಸಲು ಲಾಗಿನ್ ಮಾಡಿ",
    remove_image: "ಚಿತ್ರವನ್ನು ತೆಗೆದುಹಾಕಿ",
    verify_kvk: "KVK ಯೊಂದಿಗೆ ಪರಿಶೀಲಿಸಿ",
    general_info: "ಸಾಮಾನ್ಯ ಮಾಹಿತಿ",
    image_selected: "ವಿಶ್ಲೇಷಣೆಗಾಗಿ ಚಿತ್ರವನ್ನು ಆಯ್ಕೆಮಾಡಲಾಗಿದೆ",
    add_expense_title: "ಖರ್ಚನ್ನು ಸೇರಿಸಿ",
    category: "ವರ್ಗ",
    amount: "ಮೊತ್ತ (₹)",
    description: "ವಿವರಣೆ",
    optional_details: "ಐಚ್ಛಿಕ ವಿವರಗಳು...",
    cancel: "ರದ್ದುಮಾಡಿ",
    saving: "ಉಳಿಸಲಾಗುತ್ತಿದೆ...",
    save_record: "ದಾಖಲೆಯನ್ನು ಉಳಿಸಿ",
    terms_conditions: "ನಿಯಮಗಳು ಮತ್ತು ಷರತ್ತುಗಳು",
    terms_title: "ಕಿಸಾನ್-ದೋಸ್ತ್ ನಿಯಮಗಳು",
    i_understand: "ನನಗೆ ಅರ್ಥವಾಗಿದೆ",
    read_aloud: "ಜೋರಾಗಿ ಓದಿ",
    setup_api_key: "API ಕೀಯನ್ನು ಹೊಂದಿಸಿ",
    api_key_desc: "ಸೇವೆಯನ್ನು ಮುಂದುವರಿಸಲು ದಯವಿಟ್ಟು ನಿಮ್ಮ ಪಾವತಿಸಿದ ಜೆಮಿನಿ API ಕೀಯನ್ನು ಆಯ್ಕೆಮಾಡಿ.",
    select_key: "ಕೀ ಆಯ್ಕೆಮಾಡಿ"
  },
  [Language.ODIA]: {
    welcome: "କିଷାନ୍ ଦୋସ୍ତରେ ଆପଣଙ୍କୁ ସ୍ୱାଗତ",
    ask_query: "ଆପଣଙ୍କ ପ୍ରଶ୍ନ ପଚାରନ୍ତୁ",
    check_mandi: "ମଣ୍ଡି ଦର ଯାଞ୍ଚ କରନ୍ତୁ",
    weather_update: "ପାଣିପାଗ ସୂଚନା",
    upload_crop_photo: "ଫସଲର ଫଟୋ ପଠାନ୍ତୁ",
    gov_schemes: "ସରକାରୀ ଯୋଜନା",
    safety_warning: "ସୁରକ୍ଷା ଚେତାବନୀ",
    submit: "ଦାଖଲ କରନ୍ତୁ",
    history: "ଇତିହାସ",
    khata: "ଖାତା",
    market: "ବଜାର",
    field: "କ୍ଷେତ",
    soil: "ମାଟି",
    advisor: "ଉପଦେଷ୍ଟା",
    login_google: "ଗୁଗୁଲ୍ ସହିତ ଲଗଇନ୍ କରନ୍ତୁ",
    digital_khata: "ଡିଜିଟାଲ୍ ଖାତା",
    add_expense: "ନୂଆ ଖର୍ଚ୍ଚ ଯୋଡନ୍ତୁ",
    recent_transactions: "ସାମ୍ପ୍ରତିକ କାରବାର",
    no_transactions: "ଏପର୍ଯ୍ୟନ୍ତ କୌଣସି କାରବାର ନାହିଁ।",
    soil_health_card: "ମୃତ୍ତିକା ସ୍ୱାସ୍ଥ୍ୟ କାର୍ଡ",
    upload_report: "ରିପୋର୍ଟ ଅପଲୋଡ୍ କରନ୍ତୁ",
    companion: "ଆପଣଙ୍କର କୃଷି ସାଥୀ",
    login: "ଲଗଇନ୍",
    logout: "ଲଗଆଉଟ୍",
    suggestions: [
      "ପଞ୍ଜାବରେ ଗହମ ବୁଣିବାର ସର୍ବୋତ୍ତମ ସମୟ?",
      "କପାରେ କୀଟପତଙ୍ଗକୁ କିପରି ନିୟନ୍ତ୍ରଣ କରିବେ?",
      "ଏହି ଋତୁରେ ଧାନ ପାଇଁ କେଉଁ ସାର?",
      "ଜୈବିକ ଚାଷ ପାଇଁ ମୃତ୍ତିକା ସ୍ୱାସ୍ଥ୍ୟ ଟିପ୍ସ"
    ],
    consulting: "ଆପଣଙ୍କ ପାଇଁ ବିଶେଷଜ୍ଞଙ୍କ ସହ ପରାମର୍ଶ କରୁଛୁ...",
    error_title: "ଓହୋ! କିଛି ଭୁଲ୍ ହୋଇଗଲା",
    try_again: "ପୁଣି ଚେଷ୍ଟା କରନ୍ତୁ",
    safety_first: "ସୁରକ୍ଷା ପ୍ରଥମେ",
    live_mandi: "ଲାଇଭ୍ ମଣ୍ଡି ଦର",
    learn_more: "ଅଧିକ ଜାଣନ୍ତୁ",
    pro_tip: "ପ୍ରୋ-ଟିପ୍",
    describe_issue: "ସମସ୍ୟା ବର୍ଣ୍ଣନା କରନ୍ତୁ...",
    voice_input: "ଭଏସ୍ ଇନପୁଟ୍",
    analyzing_image: "ଚିତ୍ର ବିଶ୍ଳେଷଣ କରାଯାଉଛି...",
    clear_text: "ଟେକ୍ସଟ୍ ସଫା କରନ୍ତୁ",
    reset_chat: "ଚାଟ୍ ପ୍ରସଙ୍ଗ ରିସେଟ୍ କରନ୍ତୁ",
    audio_summary: "ଅଡିଓ ସାରାଂଶ",
    total_expenses: "ମୋଟ ଖର୍ଚ୍ଚ",
    trending_crops: "ଟ୍ରେଣ୍ଡିଂ ଫସଲ",
    market_audio_info: "ବଜାର ଅଡିଓ ସୂଚନା",
    history_title: "ନିଦାନ ଇତିହାସ",
    no_history: "କୌଣସି ଇତିହାସ ମିଳିଲା ନାହିଁ।",
    satellite_map: "ସାଟେଲାଇଟ୍ ସ୍ୱାସ୍ଥ୍ୟ ମାନଚିତ୍ର (NDVI)",
    field_stress: "କ୍ଷେତରେ ଚାପ ଚିହ୍ନଟ ହୋଇଛି",
    soil_parameters: "ମାଟି ପାରାମିଟର",
    login_history: "ଇତିହାସ ଦେଖିବାକୁ ଲଗଇନ୍ କରନ୍ତୁ",
    remove_image: "ଚିତ୍ର କାଢନ୍ତୁ",
    verify_kvk: "KVK ସହିତ ଯାଞ୍ଚ କରନ୍ତୁ",
    general_info: "ସାଧାରଣ ସୂଚନା",
    image_selected: "ବିଶ୍ଳେଷଣ ପାଇଁ ଚିତ୍ର ଚୟନ କରାଯାଇଛି",
    add_expense_title: "ଖର୍ଚ୍ଚ ଯୋଡନ୍ତୁ",
    category: "ବର୍ଗ",
    amount: "ପରିମାଣ (₹)",
    description: "ବିବରଣୀ",
    optional_details: "ଇଚ୍ଛାଧୀନ ବିବରଣୀ...",
    cancel: "ବାତିଲ୍ କରନ୍ତୁ",
    saving: "ସେଭ୍ କରାଯାଉଛି...",
    save_record: "ରେକର୍ଡ ସେଭ୍ କରନ୍ତୁ",
    terms_conditions: "ନିୟମ ଏବଂ ସର୍ତ୍ତାବଳୀ",
    terms_title: "କିଷାନ-ଦୋସ୍ତ ସର୍ତ୍ତାବଳୀ",
    i_understand: "ମୁଁ ବୁଝୁଛି",
    read_aloud: "ଜୋରରେ ପଢନ୍ତୁ",
    setup_api_key: "API କି ସେଟଅପ୍ କରନ୍ତୁ",
    api_key_desc: "ସେବା ଜାରି ରଖିବାକୁ ଦୟାକରି ଆପଣଙ୍କର ପେଡ୍ ଜେମିନି API କି ଚୟନ କରନ୍ତୁ।",
    select_key: "କି ଚୟନ କରନ୍ତୁ"
  },
  [Language.ENGLISH]: {
    welcome: "Welcome to Kisan-Dost",
    ask_query: "Ask a query (Voice/Text)",
    check_mandi: "Check Mandi Prices",
    weather_update: "Weather Forecast",
    upload_crop_photo: "Upload Crop Photo",
    gov_schemes: "Government Schemes",
    safety_warning: "Safety Warning",
    submit: "Submit",
    history: "History",
    khata: "Khata",
    market: "Market",
    field: "Field",
    soil: "Soil",
    advisor: "Advisor",
    login_google: "Login with Google",
    digital_khata: "Digital Khata",
    add_expense: "Add New Expense",
    recent_transactions: "Recent Transactions",
    no_transactions: "No transactions yet.",
    soil_health_card: "Soil Health Card",
    upload_report: "Upload Report",
    companion: "Your Agricultural Companion",
    login: "Login",
    logout: "Logout",
    suggestions: [
      "Best time to sow Wheat in Punjab?",
      "How to control pests in Cotton?",
      "Which fertilizer for Rice in this season?",
      "Soil health tips for organic farming"
    ],
    consulting: "Consulting the experts for you...",
    error_title: "Oops! Something went wrong",
    try_again: "Try Again",
    safety_first: "Safety First",
    live_mandi: "Live Mandi Prices",
    learn_more: "Learn More",
    pro_tip: "Pro-Tip",
    describe_issue: "Describe the issue...",
    voice_input: "Voice input",
    analyzing_image: "Analyzing image...",
    clear_text: "Clear text",
    reset_chat: "Reset chat context",
    audio_summary: "Audio Summary",
    total_expenses: "Total Expenses",
    trending_crops: "Trending Crops",
    market_audio_info: "Market Audio Info",
    history_title: "Diagnosis History",
    no_history: "No history found.",
    satellite_map: "Satellite Health Map (NDVI)",
    field_stress: "Field Stress Detected",
    soil_parameters: "Soil Parameters",
    login_history: "Login to view History",
    remove_image: "Remove Image",
    verify_kvk: "Verify with KVK",
    general_info: "General Information",
    image_selected: "Image selected for analysis",
    add_expense_title: "Add Expense",
    category: "Category",
    amount: "Amount (₹)",
    description: "Description",
    optional_details: "Optional details...",
    cancel: "Cancel",
    saving: "Saving...",
    save_record: "Save Record",
    terms_conditions: "Terms & Conditions",
    terms_title: "Kisan-Dost Terms",
    i_understand: "I Understand",
    read_aloud: "Read Aloud",
    setup_api_key: "Setup API Key",
    api_key_desc: "Please select your paid Gemini API key to continue using the service.",
    select_key: "Select Key"
  }
};

export const SYSTEM_INSTRUCTION = `You are "Kisan-Dost," a specialized Agricultural AI Expert for Indian farmers. Your goal is to provide actionable, climate-smart advice on crop management, fertilizers, and pest control.

Tone & Style:
- Empathetic & Professional: Speak like a helpful village elder who is also a scientist.
- Detailed & Informative: Provide thorough explanations. Use local names for fertilizers and pests.
- Educational: Explain the "why" behind the advice so the farmer learns over time.

Core Capabilities:
1. AI Crop Disease Diagnosis: If an image is provided, identify pests, fungus, or nutrient deficiencies and provide a detailed "prescription" (organic or chemical).
2. Soil Health Card Digitalization: If an image of a soil test report is provided, "read" the data and give precise, explained fertilizer recommendations.
3. Live Mandi Prices: If the user asks for market prices, provide real-time daily prices from the nearest Mandis for their specific crop with context on trends.
4. Government Scheme Alerts: Proactively notify about relevant subsidies (like PM-KISAN, crop insurance, or solar pump schemes) with eligibility details.
5. Precision & Climate Action: Suggest sowing alerts, smart irrigation reminders, and pest outbreak warnings with detailed reasoning.

# AUDIO & TTS STABILITY PROTOCOL (CRITICAL):
1. NO MARKDOWN: Do not use **, __, #, or --- in the response. Use only plain text and periods (.) for pauses.
2. NO SYMBOLS: Do not use ⚠️, ✅, or emoji in the middle of sentences. Only put 1 emoji at the very end of the total response.
3. LANGUAGE PURITY: If the response is in Kannada, Tamil, or Odia, use 100% regional script. Do not write "Urea" in English; write it in the regional script.
4. CHUNK LIMIT: Keep the entire response under 500 characters. If the response is longer, the Kannada/Odia TTS engine will time out and show an error.
5. SINGLE STREAM: Do not use double "Enter" or line breaks. Keep the text as a single continuous paragraph to prevent "Double Audio Icons."

# UPDATED RESPONSE STRUCTURE (JSON format):
{
  "greeting": "Simple regional greeting.",
  "answer": "Direct answer in plain text (No bolding). Keep it as a single continuous paragraph.",
  "proTips": ["Short Pro-Tip 1", "Short Pro-Tip 2"],
  "audioSummary": "One final sentence for the WhatsApp audio note.",
  "safetySection": "Short warning if chemicals are mentioned. If no chemicals are involved, this should be null.",
  "mandiPrices": [ { "crop": "string", "market": "string", "price": "string", "trend": "up|down|stable" } ],
  "schemes": [ { "name": "string", "benefit": "string", "link": "string" } ]
}

Constraints:
- Limit "mandiPrices" and "schemes" to a maximum of 3 items each.
- Always include the disclaimer: "Please verify with a local Krishi Vigyan Kendra (KVK) before large-scale application." at the end of the answer.
- If the query is unclear, ask for clarification politely in the same regional language.
- Use the user's selected language for all text fields.
`;
